### ISSUE TITLE
get_token error

### ISSUE THREAD

**Issue by rascasse83** [soodoku/clarifai#3]
Hi
I get this error message when running get_token()

Error: unexpected symbol in:
"  
get_token"

it has recognised the secret_id parameters though (used Sys.getenv to check)

library(clarifai)
secret_id(c("lruLGQlebkD06FzoYBblhe9z010rtEpDTbltTGXk", "Z5DpmAmhv3c9YU9svyxIYWSVNBvYYcoAg6rLPyZ_"))

Sys.getenv('ClarifaiId')
Sys.getenv('ClarifaiSecret')

get_token()

Best

**Comment by soodoku** [comment]
Thanks. It is some breaking change from another dependency. I am aware of the issue. I plan to work on it later today or early tomorrow. Apologies for the hassle.

**Comment by rascasse83** [comment]
Thanks for the response and great to see this repo being live.

**Comment by soodoku** [comment]
Hi --- I never got back to you on this, but I tried hard and couldn't replicate the issue. I hope you were able to figure it out, but if not, please re-open the issue. And please be mindful in not publishing your client id + password for the API. I would recommend deleting the application you registered. Please reopen the issue if the problem still exists but please give me a reproducible example so that I can help troubleshoot it.
